import 'base_props.dart';

/// View component properties
class ViewProps extends BaseProps {
  const ViewProps({
    super.id,
    super.testID,
    super.accessible,
    super.accessibilityLabel,
    super.style,
    super.pointerEvents,
    super.width,
    super.height,
    super.margin,
    super.marginTop,
    super.marginRight,
    super.marginBottom,
    super.marginLeft,
    super.padding,
    super.paddingTop,
    super.paddingRight,
    super.paddingBottom,
    super.paddingLeft,
    super.flexDirection,
    super.justifyContent,
    super.alignItems,
    super.alignSelf,
    super.flex,
    super.flexGrow,
    super.flexShrink,
    super.flexBasis,
    super.backgroundColor,
    super.opacity,
    super.borderRadius,
    super.borderTopLeftRadius,
    super.borderTopRightRadius,
    super.borderBottomLeftRadius,
    super.borderBottomRightRadius,
    super.borderColor,
    super.borderWidth,
    super.transform,
    super.shadowColor,
    super.shadowOpacity,
    super.shadowRadius,
    super.shadowOffset,
    super.overflow,
    super.zIndex,
    super.position,
    super.top,
    super.right,
    super.bottom,
    super.left,
  });
}
