platform :ios, '13.5'

target 'Runner' do
  use_frameworks!

  pod 'Yoga', :git => 'https://github.com/squirelboy360/yoga.git'
  pod 'Kingfisher', '~> 8.3'
end

target 'RunnerTests' do
  inherit! :search_paths
end
